# -*- coding: utf-8 -*-
"""multi_lingual Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKARB9wpfp9q5znO2pha6VhI5Iao7Pjc
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# List the contents of the mounted Google Drive
print('Listing contents of /content/drive:')
!ls -F '/content/drive/'

# You can also explore specific directories, for example:
# print('\nListing contents of MyDrive:')
# !ls -F '/content/drive/MyDrive/'

print('Listing contents of MyDrive to find the shared folder:')
!ls -F '/content/drive/MyDrive/'

# Once you see the folder name, you can navigate into it, e.g.:
# !ls -F '/content/drive/MyDrive/Name_Of_Shared_Folder/'

print('Listing contents of the specified folder:')
!ls -F '/content/drive/MyDrive/amazon multilingual data/'

!pip install transformers datasets sentencepiece

from datasets import load_dataset

# Define the path to your training CSV file
train_csv_path = '/content/drive/MyDrive/amazon multilingual data/train.csv'

# Load the dataset
dataset = load_dataset('csv', data_files={'train': train_csv_path})

def convert_label(example):
    # Assuming the 'stars' column exists in your dataset for sentiment analysis
    if example["stars"] <= 2:
        example["label"] = 0
    elif example["stars"] == 3:
        example["label"] = 1
    else:
        example["label"] = 2
    return example

# Apply the conversion to the 'train' split of the dataset
dataset = dataset.map(convert_label)

from transformers import MarianMTModel, MarianTokenizer

model_name = "Helsinki-NLP/opus-mt-en-de"
translator_tokenizer = MarianTokenizer.from_pretrained(model_name)
translator_model = MarianMTModel.from_pretrained(model_name)

def demonstrate_translator_working(input_text):
    """
    Translates an English input text to German using the initialized MarianMTModel.
    Assumes `translator_tokenizer`, `translator_model`, and the `translate` function
    (from cell XceUj436fofe) are globally available.
    """
    print(f"Original English text: {input_text}")
    # The 'translate' function is assumed to be defined in a subsequent cell (XceUj436fofe) and already executed.
    # It expects a list of texts.
    translated_texts = translate([input_text])
    if translated_texts:
        print(f"Translated German text: {translated_texts[0]}")
    else:
        print("Translation failed or returned no text.")

# Call the demonstration function to show its working
print("\n--- Demonstrating MarianMTModel translation ---")
demonstrate_translator_working("This is a sample sentence to demonstrate the translation.")
demonstrate_translator_working("The quick brown fox jumps over the lazy dog.")
print("---------------------------------------------")

def translate(texts):
    batch = translator_tokenizer(texts, return_tensors="pt", padding=True, truncation=True)
    generated = translator_model.generate(**batch)
    return translator_tokenizer.batch_decode(generated, skip_special_tokens=True)

from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "xlm-roberta-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3
)

class CrossLingualLoss(torch.nn.Module):
    def __init__(self, tau=0.07):
        super().__init__()
        self.tau = tau

    def embedding_loss(self, h1, h2):
        return torch.mean((h1 - h2) ** 2)

    def symmetric_kl(self, logits1, logits2):
        p1 = F.log_softmax(logits1, dim=-1)
        p2 = F.softmax(logits2, dim=-1)
        kl1 = F.kl_div(p1, p2, reduction='batchmean')

        p2_log = F.log_softmax(logits2, dim=-1)
        p1_soft = F.softmax(logits1, dim=-1)
        kl2 = F.kl_div(p2_log, p1_soft, reduction='batchmean')

        return kl1 + kl2

    def contrastive_loss(self, h1, h2):
        sim = F.cosine_similarity(h1, h2)
        return torch.mean(1 - sim)

from torch.utils.data import DataLoader
from transformers import DataCollatorWithPadding

# Define a tokenization function
def tokenize_function(examples):
    return tokenizer(examples["review_body"], truncation=True)

# Apply tokenization to the dataset
tokenized_dataset = dataset.map(tokenize_function, batched=True)

# Remove columns that are not needed for training
# These columns might interfere with the DataCollatorWithPadding trying to convert them to tensors
tokenized_dataset = tokenized_dataset.remove_columns(["review_id", "product_id", "review_body", "stars"])

# Initialize DataCollatorWithPadding
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# Create a DataLoader for the training set
dataloader = DataLoader(
    tokenized_dataset["train"],
    shuffle=True,
    batch_size=16, # You can adjust your batch size here
    collate_fn=data_collator
)

import torch
import torch.nn as nn
import torch.nn.functional as F

class EmotionConfidenceGatedLoss(nn.Module):
    def __init__(self, tau=0.07):
        super().__init__()
        self.tau = tau

    # ---------------------------
    # 1. Embedding Alignment
    # ---------------------------
    def embedding_loss(self, z1, z2):
        return F.mse_loss(z1, z2)

    # ---------------------------
    # 2. Symmetric KL Divergence
    # ---------------------------
    def symmetric_kl(self, logits1, logits2):
        T = self.tau

        p1_log = F.log_softmax(logits1 / T, dim=-1)
        p2 = F.softmax(logits2 / T, dim=-1)
        kl1 = F.kl_div(p1_log, p2, reduction='batchmean') * (T ** 2)

        p2_log = F.log_softmax(logits2 / T, dim=-1)
        p1 = F.softmax(logits1 / T, dim=-1)
        kl2 = F.kl_div(p2_log, p1, reduction='batchmean') * (T ** 2)

        return kl1 + kl2

    # ---------------------------
    # 3. Contrastive Loss
    # ---------------------------
    def contrastive_loss(self, z1, z2):
        z1 = F.normalize(z1, dim=-1)
        z2 = F.normalize(z2, dim=-1)

        logits = torch.matmul(z1, z2.T) / self.tau
        labels = torch.arange(z1.size(0)).to(z1.device)

        return F.cross_entropy(logits, labels)

    # ---------------------------
    # 4. Confidence Gate
    # ---------------------------
    def confidence_gate(self, logits):
        probs = F.softmax(logits, dim=-1)
        entropy = -torch.sum(probs * torch.log(probs + 1e-8), dim=-1)

        max_entropy = torch.log(torch.tensor(logits.size(-1), device=logits.device))
        normalized_entropy = entropy / max_entropy

        confidence = 1 - normalized_entropy
        return confidence

    # ---------------------------
    # 5. Emotion Gate
    # ---------------------------
    def emotion_gate(self, z):
        intensity = torch.norm(z, dim=-1)
        intensity = (intensity - intensity.min()) / (intensity.max() - intensity.min() + 1e-8)
        return intensity

    # ---------------------------
    # 6. Forward (Gated Loss)
    # ---------------------------
    def forward(self, ce_loss, logits1, logits2, z1, z2):

        kl = self.symmetric_kl(logits1, logits2)
        embed = self.embedding_loss(z1, z2)
        contrast = self.contrastive_loss(z1, z2)

        # Compute gates
        confidence = self.confidence_gate(logits1)
        emotion = self.emotion_gate(z1)

        alpha = 0.5 * confidence + 0.5 * emotion
        alpha = alpha.mean()

        # Apply gating
        gated_kl = alpha * kl
        gated_embed = alpha * embed
        gated_contrast = alpha * contrast

        total_loss = ce_loss + gated_kl + gated_embed + gated_contrast

        return total_loss, {
            "ce": ce_loss.item(),
            "kl": kl.item(),
            "embed": embed.item(),
            "contrast": contrast.item(),
            "alpha": alpha.item()
        }